name: Ubuntu

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      #- name: 'Install dependencies'
      #  run: |
      #    sudo apt-get update
      #    #sudo apt-get install --fix-missing cmake

      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Build'
        run: |
          cd lib
          mkdir build
          cd build
          cmake .. -DYUKINO_TEST=1
          make
          cd ../..

      - name: 'Run test suite'
        run: |
          cd lib/build
          make test
          cd ../..
